# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test:
    docker:
      - image: golang:1.8-alpine
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - run:
          name: Install glide
          command: go get github.com/Masterminds/glide
      - run:
          name: Install ginkgo
          command: go get github.com/onsi/ginkgo/ginkgo
      - run:
          name: Test
          command: ginkgo -r --progress tests/quorum

workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
